version: '2'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=group_db
      - MYSQL_ROOT_HOST=0.0.0.0 
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

